services:
  redis:
    image: redis:7-alpine
    ports:
      - '6380:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 2s
      timeout: 5s
      retries: 10

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: quizzy
      POSTGRES_PASSWORD: quizzy
      POSTGRES_DB: quizzy
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U quizzy -d quizzy']
      interval: 2s
      timeout: 5s
      retries: 10
